# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Input & Output
email: i@claws.se
description: > # this means to ignore newlines until "baseurl:"
  My name is Claes Sahlström and I like building stuff that scales. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://claws.se"
twitter_username: claws_se
github_username:  claws-se

# Build settings
markdown: kramdown
